version: "3.7"

volumes:
  postresql_data: {}
  redis_data: {}
  app_shared: {}
  elasticsearch_data: {}
  https_portal: {}

services:
  nginx:
    image: "docker.io/library/nginx:1.20.1"
    container_name: "evemonk_nginx"
    restart: "unless-stopped"
    volumes:
      - "app_shared:/shared"
      - "./nginx-evemonk.conf:/etc/nginx/conf.d/default.conf:ro"

  https_portal:
    image: "docker.io/steveltn/https-portal:1.19.0"
    container_name: "evemonk_https_portal"
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "https_portal:/var/lib/https-portal"
    environment:
      STAGE: "production"
      WEBSOCKET: "true"
      LISTEN_IPV6: "true"
      DOMAINS: "evemonk.com -> http://nginx,
                api.evemonk.com -> http://nginx,
                www.evemonk.com => https://evemonk.com"

  redis:
    image: "docker.io/library/redis:6.2.3"
    container_name: "evemonk_redis"
    restart: "unless-stopped"
    volumes:
      - "redis_data:/data"

  memcached:
    image: "docker.io/library/memcached:1.6.9"
    container_name: "evemonk_memcached"
    restart: "unless-stopped"
    command: "memcached -m 64"

  postgresql:
    image: "docker.io/library/postgres:13.3"
    container_name: "evemonk_postgresql"
    restart: "unless-stopped"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "postresql_data:/var/lib/postgresql/data"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    container_name: "evemonk_elasticsearch"
    restart: "unless-stopped"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"

  backend:
    image: "docker.io/biow0lf/evemonk:0.4.26"
    container_name: "evemonk_backend"
    restart: "unless-stopped"
    env_file: ".env"
    command: "./bin/backend"
    volumes:
      - "app_shared:/shared"
      - "./newrelic.yml:/app/config/newrelic.yml:ro"
      - "/srv/static/sde-20210527:/app/static:ro"
    ports:
      - "3000:3000"

  sidekiq:
    image: "docker.io/biow0lf/evemonk:0.4.26"
    container_name: "evemonk_sidekiq"
    restart: "unless-stopped"
    env_file: ".env"
    command: "./bin/sidekiq"
    volumes:
      - "app_shared:/shared"
      - "./newrelic.yml:/app/config/newrelic.yml:ro"
      - "/srv/static/sde-20210527:/app/static:ro"

  cron:
    image: "docker.io/biow0lf/evemonk:0.4.26"
    container_name: "evemonk_cron"
    restart: "unless-stopped"
    env_file: ".env"
    command: "./bin/cron"
    volumes:
      - "app_shared:/shared"
      - "./newrelic.yml:/app/config/newrelic.yml:ro"
      - "/srv/static/sde-20210527:/app/static:ro"
