version: "3.7"

volumes:
  postresql_data: {}
  redis_data: {}
  app_shared: {}
  elasticsearch_data: {}
  https_portal: {}

services:
  nginx:
    image: "nginx:1.18.0"
    container_name: "evemonk_nginx"
    restart: "unless-stopped"
    volumes:
      - "app_shared:/shared"
      - "./nginx-evemonk.conf:/etc/nginx/conf.d/default.conf:ro"

  https_portal:
    image: "steveltn/https-portal:1.12.0"
    container_name: "evemonk_https_portal"
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "https_portal:/var/lib/https-portal"
    environment:
      STAGE: "production"
      WEBSOCKET: "true"
      DOMAINS: "evemonk.com -> http://nginx,
                api.evemonk.com -> http://nginx,
                www.evemonk.com => https://evemonk.com"

  redis:
    image: "redis:6.0.8"
    container_name: "evemonk_redis"
    restart: "unless-stopped"
    volumes:
      - "redis_data:/data"

  memcached:
    image: "memcached:1.6.7"
    container_name: "evemonk_memcached"
    restart: "unless-stopped"
    command: "memcached -m 64"

  postgresql:
    image: "postgres:12.4"
    container_name: "evemonk_postgresql"
    restart: "unless-stopped"
    volumes:
      - "postresql_data:/var/lib/postgresql/data"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.1"
    container_name: "evemonk_elasticsearch"
    restart: "unless-stopped"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"

  backend:
    image: "biow0lf/evemonk:0.3.10"
    container_name: "evemonk_backend"
    restart: "unless-stopped"
    env_file: ".env"
    command: "./bin/backend"
    volumes:
      - "app_shared:/shared"
      - "./newrelic.yml:/app/config/newrelic.yml:ro"
      - "/srv/static/sde-20200818:/app/static:ro"
    depends_on:
      - "redis"
      - "memcached"
      - "postgresql"
      - "elasticsearch"
    ports:
      - "3000:3000"

  sidekiq:
    image: "biow0lf/evemonk:0.3.10"
    container_name: "evemonk_sidekiq"
    restart: "unless-stopped"
    env_file: ".env"
    command: "./bin/sidekiq"
    volumes:
      - "app_shared:/shared"
      - "./newrelic.yml:/app/config/newrelic.yml:ro"
      - "/srv/static/sde-20200818:/app/static:ro"
    depends_on:
      - "redis"
      - "memcached"
      - "postgresql"
      - "elasticsearch"

  cron:
    image: "biow0lf/evemonk:0.3.10"
    container_name: "evemonk_cron"
    restart: "unless-stopped"
    env_file: ".env"
    command: "./bin/cron"
    volumes:
      - "app_shared:/shared"
      - "./newrelic.yml:/app/config/newrelic.yml:ro"
      - "/srv/static/sde-20200818:/app/static:ro"
    depends_on:
      - "redis"
      - "memcached"
      - "postgresql"
      - "elasticsearch"
