version: '3.7'

volumes:
  postresql_data:
  redis_data:
  app_shared:
  elasticsearch_data:

services:
  nginx:
    image: 'nginx:1.16.0'
    restart: unless-stopped
    volumes:
      - 'app_shared:/shared'
      - './nginx.conf:/etc/nginx/nginx.conf:ro'

  redis:
    image: 'redis:5.0.4'
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'

  memcached:
    image: 'memcached:1.5.14'
    restart: unless-stopped
    command: memcached -m 64

  postgresql:
    image: 'postgres:11.2'
    restart: unless-stopped
    volumes:
      - 'postresql_data:/var/lib/postgresql/data'

  elasticsearch:
    image: 'elasticsearch:7.0.1'
    restart: unless-stopped
    volumes:
      - 'elasticsearch_data:/usr/share/elasticsearch/data'

  backend:
    image: 'biow0lf/evemonk:latest'
    env_file: .env
    restart: unless-stopped
    entrypoint: ./bin/app.sh
    volumes:
      - 'app_shared:/shared'
    depends_on:
      - redis
      - memcached
      - postgresql
      - elasticsearch
    ports:
      - '3000:3000'

  sidekiq:
    image: 'biow0lf/evemonk:latest'
    env_file: .env
    restart: unless-stopped
    entrypoint: ./bin/sidekiq.sh
    depends_on:
      - redis
      - memcached
      - postgresql
      - elasticsearch
